INSERT INTO boutique_category (type, added_on, order_no, status, title) VALUES
('EthnicWear', NOW(), 1, 'ACTIVE', 'Sarees'),
('WesternWear', NOW(), 2, 'ACTIVE', 'Dresses'),
('PartyWear', NOW(), 3, 'ACTIVE', 'Gowns'),
('CasualWear', NOW(), 4, 'ACTIVE', 'Tops & Jeans'),
('KidsWear', NOW(), 5, 'ACTIVE', 'Baby & Kids Clothing'),
('Accessories', NOW(), 6, 'ACTIVE', 'Bags & Wallets'),
('Jewellery', NOW(), 7, 'ACTIVE', 'Necklaces & Earrings'),
('Footwear', NOW(), 8, 'ACTIVE', 'Heels & Sandals'),
('BridalWear', NOW(), 9, 'ACTIVE', 'Wedding Sarees'),
('WinterWear', NOW(), 10, 'INACTIVE', 'Jackets & Coats'),
('SummerCollection', NOW(), 11, 'ACTIVE', 'Summer Dresses'),
('FormalWear', NOW(), 12, 'ACTIVE', 'Office Wear'),
('Sportswear', NOW(), 13, 'ACTIVE', 'Yoga & Gym Clothes'),
('LoungeWear', NOW(), 14, 'ACTIVE', 'Comfort Wear'),
('EthnicAccessories', NOW(), 15, 'ACTIVE', 'Dupattas & Shawls'),
('Handmade', NOW(), 16, 'ACTIVE', 'Artisan Collections'),
('HomeWear', NOW(), 17, 'ACTIVE', 'Night Suits & Pajamas'),
('Luxury', NOW(), 18, 'ACTIVE', 'Designer Outfits'),
('BeachWear', NOW(), 19, 'ACTIVE', 'Swimwear & Coverups'),
('FestivalWear', NOW(), 20, 'ACTIVE', 'Diwali & Navratri Special'),
('DenimCollection', NOW(), 21, 'ACTIVE', 'Jeans & Jackets'),
('EthnicShoes', NOW(), 22, 'ACTIVE', 'Mojaris & Kolhapuris'),
('CasualShoes', NOW(), 23, 'ACTIVE', 'Sneakers & Loafers'),
('LuxuryJewellery', NOW(), 24, 'ACTIVE', 'Gold & Diamond Sets'),
('Handbags', NOW(), 25, 'ACTIVE', 'Clutch & Tote Bags'),
('Scarves', NOW(), 26, 'ACTIVE', 'Silk & Cotton Scarves'),
('Belts', NOW(), 27, 'ACTIVE', 'Leather Belts'),
('Watches', NOW(), 28, 'ACTIVE', 'Luxury Watches'),
('CapsHats', NOW(), 29, 'ACTIVE', 'Summer Hats & Caps'),
('Sunglasses', NOW(), 30, 'ACTIVE', 'Fashion Sunglasses'),
('WinterAccessories', NOW(), 31, 'ACTIVE', 'Gloves & Mufflers'),
('KidsAccessories', NOW(), 32, 'ACTIVE', 'Hats & Bags'),
('ActiveWear', NOW(), 33, 'ACTIVE', 'Tracksuits & Sportswear'),
('NightWear', NOW(), 34, 'ACTIVE', 'Sleepwear & Pajamas'),
('EthnicJewellery', NOW(), 35, 'ACTIVE', 'Bangles & Earrings'),
('CasualJewellery', NOW(), 36, 'ACTIVE', 'Necklaces & Rings'),
('DesignerWear', NOW(), 37, 'ACTIVE', 'Designer Sarees & Gowns'),
('HandcraftedWear', NOW(), 38, 'ACTIVE', 'Handloom Sarees'),
('PartyAccessories', NOW(), 39, 'ACTIVE', 'Clutch & Jewelry Sets'),
('WeddingAccessories', NOW(), 40, 'ACTIVE', 'Veils & Hair Accessories'),
('YogaWear', NOW(), 41, 'ACTIVE', 'Yoga Pants & Tops'),
('GymAccessories', NOW(), 42, 'ACTIVE', 'Water Bottles & Bags'),
('BeachAccessories', NOW(), 43, 'ACTIVE', 'Beach Bags & Towels'),
('FormalAccessories', NOW(), 44, 'ACTIVE', 'Ties & Cufflinks'),
('CasualWearMen', NOW(), 45, 'ACTIVE', 'Shirts & T-Shirts'),
('CasualWearWomen', NOW(), 46, 'ACTIVE', 'Blouses & Skirts'),
('FootwearMen', NOW(), 47, 'ACTIVE', 'Formal Shoes & Loafers'),
('FootwearWomen', NOW(), 48, 'ACTIVE', 'Heels & Flats'),
('SeasonalWear', NOW(), 49, 'ACTIVE', 'Monsoon & Summer Collection'),
('SpecialEdition', NOW(), 50, 'ACTIVE', 'Limited Edition Outfits');